export const JobData = [
    {
        id: 0,
        position: "Janitor",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to clean the bathroom stalls",
        pay: "20k-30k",
        age: "6 days",
        location: "On-site",
        type: "Internship",
        domain: "Health",
        education: "Highschool",
        skills: ["Cleaning", "Communication", "Graphic Design", "Python", "C++", "Photoshop", "Dancing", "Singing"]
    },
    {
        id: 1,
        position: "Painter",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to paint the bathroom stalls",
        pay: "25k-35k",
        age: "7 days",
        location: "On-site",
        type: "Internship",
        domain: "Art",
        education: "Highschool",
        skills: ["Cleaning", "Communication"]
    },
    {
        id: 2,
        position: "Painter",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to paint the bathroom stalls",
        pay: "25k-35k",
        age: "7 days",
        location: "On-site",
        type: "Internship",
        domain: "Art",
        education: "Highschool",
        skills: ["Cleaning", "Communication"]
    },
    {
        id: 3,
        position: "Painter",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to paint the bathroom stalls",
        pay: "25k-35k",
        age: "7 days",
        location: "On-site",
        type: "Internship",
        domain: "Art",
        education: "Highschool",
        skills: ["Cleaning", "Communication"]
    },
    {
        id: 4,
        position: "Painter",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to paint the bathroom stalls",
        pay: "25k-35k",
        age: "7 days",
        location: "On-site",
        type: "Internship",
        domain: "Art",
        education: "Highschool",
        skills: ["Cleaning", "Communication"]
    },
    {
        id: 5,
        position: "Painter",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to paint the bathroom stalls",
        pay: "25k-35k",
        age: "7 days",
        location: "On-site",
        type: "Internship",
        domain: "Art",
        education: "Highschool",
        skills: ["Cleaning", "Communication"]
    },
    {
        id: 6,
        position: "Painter",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to paint the bathroom stalls",
        pay: "25k-35k",
        age: "7 days",
        location: "On-site",
        type: "Internship",
        domain: "Art",
        education: "Highschool",
        skills: ["Cleaning", "Communication"]
    },
    {
        id: 7,
        position: "Painter",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to paint the bathroom stalls",
        pay: "25k-35k",
        age: "7 days",
        location: "On-site",
        type: "Internship",
        domain: "Art",
        education: "Highschool",
        skills: ["Cleaning", "Communication"]
    },
    {
        id: 8,
        position: "Painter",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to paint the bathroom stalls",
        pay: "25k-35k",
        age: "7 days",
        location: "On-site",
        type: "Internship",
        domain: "Art",
        education: "Highschool",
        skills: ["Cleaning", "Communication"]
    },
    {
        id: 9,
        position: "Painter",
        company: "FAST-NUCES",
        city: "Lahore",
        country: "Pakistan",
        description: "From the windows to the walls, we need someone to paint the bathroom stalls",
        pay: "25k-35k",
        age: "7 days",
        location: "On-site",
        type: "Internship",
        domain: "Art",
        education: "Highschool",
        skills: ["Cleaning", "Communication"]
    },   
]